table table1 as t {
    id int [pk]
    t2_ref int [ref: > table2.id]
    name varchar [unique, not null default: `testing`]
    b1 bool [default: true]
    b2 boolean [default: false]
    b2 boolean [default: null]
    i1 int
}

Table dsadsa {
    id int [pk]
    dasdsa dfdsfd
}
Table table2 {
    id integer [primary key]
    indexes: {
        abc [unique]
    }
}

table table3 as t3 {}

Table table4 as t4 {}

Enum e_values {
    val1
}